code-section:
    type: select
    after-string: '] '
    before-string: '['
    destination: title
    instructions: Which section of the codebase?
    modifiable: true
    options:
        - input
        - git
        - interface
        - documentation
        - core
        - git
        - configuration
change-type:
    type: select
    modifiable: true
    after-string: ': '
    destination: title
    instructions: What kind of change?
    options:
        - fix
        - enhancement
        - refactoring
commit-title:
    type: text
    destination: title
    placeholder: Commit Title
commit-description:
    type: multiline-text
    allow-empty: true
    destination: body
    instructions: Please describe your changes.
ticket-number:
    type: text
    allow-empty: true
    before-string: "\n\nTicket: "
    data-type: integer
    destination: body
    instructions: "Associated Ticket Number (if any)"
tags:
    type: multi-select
    allow-empty: true
    modifiable: true
    before-string: "\n\nTags: "
    destination: body
    empty-selection-text: Don't Tag
    instructions: "(optional) add relevant tags"
    options:
        - hotfix
        - dependencies
        - tech-debt
        - refactoring
    record-as: joined-string
